#!/usr/bin/bash

# GENERATED BY CHATGPT

# Check if pandoc is installed
if ! command -v pandoc &> /dev/null; then
    echo "Error: pandoc is not installed."
    exit 1
fi

# Loop through all .md files in the current directory
for file in *.md; do
    # Skip if no .md files found
    [ -e "$file" ] || continue

    # Get the base name without extension
    base="${file%.md}"
    
    # Convert to HTML using pandoc
    pandoc "$file" -s -o "../${base}.html"
    
    echo "Converted $file to ${base}.html"
done
